# Perpetual Calendar

A perpetual calendar is a calendar designed to be valid for many years, usually designed to look up the day of the week for a given date in the future. 

__Algorithm__:

* A year is a leap year if it is divisible by 4, unless the year is divisible by 100, in which case the year must also be divisible by 400. In other words, the years 1996, 2000, 2004, 2008, 2012, 2016, and 2020 are all leap years. However, the years 1700, 1900, and 2100 are not leap years. The first set of years are all divisible by 4, and the only year that is divisible by 100 (2000) is also divisible by 400. The second set of years are all divisible by 100, but none of them are divisible by 400.

In [ ]:
# This imports all the functions in your file so that they can be used in the notebook.
from pcalendar import *

print(is_leap(1900)) #should print False
print(is_leap(2000)) #should print True
print(is_leap(2004)) #should print True
print(is_leap(2005)) #should print False
print(is_leap(2100)) #should print False
print(is_leap(2400)) #should print True

False
True
True
False
False
True


In the next two steps, `magic_month` & `day_of_year` functions will be written to determine the day of the year that a date falls on. For instance, January 1 is the first day of the year. December 31 is the 365th day of the year, but the 366th day in a leap year. 

The first step in creating this function is to create a helper function. This helper function will be called `magic_month` and it is designed to return the number of days that have gone by in a year on the first of any month (assuming it's not a leap year). For instance, on January 1, zero days have gone by in the year so far. On February 1, 31 days have gone by (because January has 31 days). On March 1, 59 days have gone by (the 31 days of January, plus the 28 days of February, assuming it's not a leap year).

The `magic_month` function takes a parameter called `month`, that will be the integer representing a month (1=January, 2=February, and so on). This function should return the number of days gone by since the beginning of the year. Here's a table of what to return:
```
January (Month #1):     0
February (Month #2):   31
March (Month #3):      59
April (Month #4):      90
May (Month #5):       120
June (Month #6):      151
July (Month #7):      181
August (Month #8):    212
September (Month #9): 243
October (Month #10):  273
November (Month #11): 304
December (Month #12): 334
```

In [2]:
from pcalendar import *
print(magic_month(1))  #should print 0
print(magic_month(2))  #should print 31
print(magic_month(7))  #should print 181
print(magic_month(9))  #should print 243
print(magic_month(11)) #should print 304

0
31
181
243
304


Now, a function called `day_of_year` will be written. That function takes three integer parameters: a month (1-12), a day (1-31), and a year (any year is possible). This function should return the day of year (1-366) that this date occurs on.

First, we need to find if the year is a leap year or not by calling the `is_leap` function on the year and capturing the return value. Next, getting the appropriate `magic_month` value for the month. The formula for finding the day of the year is quite simple:

__The day of the year is the `magic_month` number plus the day of the month. If this year is a leap year and the month is March or later, add one to this result.__

Example: Suppose we call `day_of_year(7, 29, 2019)` to calculate the day of the year for July 29, 2019. 2019 is not a leap year, and the magic_month number for July (month #7) is 181. So the day of the year here is 181 + 29, which is 210.

In [3]:
from pcalendar import *

print(day_of_year(7, 29, 2019))  #should print 210
print(day_of_year(4, 11, 2016))  #should print 102
print(day_of_year(12, 31, 2100)) #should print 365
print(day_of_year(1, 30, 2016))  #should print 30

210
102
365
30


```
Sunday: 0
Monday: 1
Tuesday: 2
Wednesday: 3
Thursday: 4
Friday: 5
Saturday: 6
```

The next function is called `new_years_day` that will calculate the day of the week number (from the table above) for any January 1 in history. Here's how it works. The steps are:

* Start with the year in question.
* Add the quotient that results from dividing the year by 4. 
* Subtract the quotient that results from dividing the year by 100.
* Add the quotient that results from dividing the year by 400.
* If your year is a leap year (call `is_leap` function!) subtract 1.
* Divide this number by 7 and take the remainder (use the percent/modulus operator). This final number is your day of the week number (the value to return).

Let's do an example. Suppose we want to find the day of the week for New Year's Day 2019.
* Begin with 2019.
* Add in 2019 // 4, which is 504. 2019 + 504 = 2523.
* Subtract 2019 // 100, which is 20. 2523 - 20 = 2503.
* Add in 2019 // 400, which is 5. 2503 + 5 = 2508.
* 2019 is not a leap year (so the number doesn't change).
* 2508 % 7 is 2, which means 2019 began on a Tuesday (you can verify this on a calendar!).

In [4]:
from pcalendar import *

print(new_years_day(1900)) #should print 1
print(new_years_day(2019)) #should print 2
print(new_years_day(2020)) #should print 3
print(new_years_day(2021)) #should print 5
print(new_years_day(2024)) #should print 1

1
2
3
5
1


The function `day_of_week` is now to be written. This function takes three parameters: the month (1-12), the day of the month (1-31), and the year. This function will finally compute the day of the week for any day of any year! Here's how it works. Call `day_of_year` function, passing in the month, day, and year parameters; and then `new_years_day` function, passing in the year parameter. If you add those values together, subtract one, divide the result by 7, and take the remainder, the day of the week (as an integer!). Return this integer value.

Here's an example. Let's find the day of the week for July 29, 2019. We already know that `day_of_year(7, 29, 2019)` returns 210, and `new_years_day(2019)` returns 2. If we add these together and subtract 1, we get 210 + 2 - 1 = 211. 211 % 7 is 1, which means July 29, 2019 falls on a Monday (check it on a calendar if you want!).

In [5]:
from pcalendar import *

print(day_of_week(7, 29, 2019))  #should print 1
print(day_of_week(7, 4, 1900))   #should print 3
print(day_of_week(2, 14, 2000))  #should print 1
print(day_of_week(12, 25, 2020)) #should print 5
print(day_of_week(10, 4, 2023))  #should print 3

1
3
1
5
3


Now, one more function called `day_of_week_str` will be written. It does the same operation as `day_of_week`, except the answer is returned as a string (like "Sunday", "Monday", etc). This function takes three parameters: the month (1-12), the day of the month (1-31), and the year. Here's how it works. Simply call day_of_week, passing in the same three parameters you are given here.

In [6]:
from pcalendar import *

print(day_of_week_str(7, 29, 2019))  #should print Monday
print(day_of_week_str(12, 25, 2020)) #should print Friday
print(day_of_week_str(10, 4, 2023))  #should print Wednesday
print(day_of_week_str(10, 31, 2056)) #should print Tuesday

Monday
Friday
Wednesday
Tuesday


* `day_of_year` should call `is_leap` and `magic_month`.
* `new_years_day` should call `is_leap`.
* `day_of_week` should call `day_of_year` and `new_years_day`.
* `day_of_week_str` should call `day_of_week`.

The main function does the following:
* Ask the user for three integers: the month, day of the month, and year. (This can be any month/day/year combination the user wants.)
* Compute and print the day of the year for this month/day/year. Do this by calling your `day_of_year` function.
* Compute and print the day of the week for this month/day/year. Do this by calling your `day_of_week_str` function.
* Compute and print the day of the week for user's month and day, but for the year 2020. Do this by calling your `day_of_week_str` function.
* Compute and print the day of the week for New Year's Day on the user's year. Do this by calling your `day_of_week_str` function.

Test the program using the examples below. Here's a sample run:
```
Pick a date, any date (such as your birthday!)
What is the month? (1-12)? 11
What is the day? 21
What is the year? 1981
This is day number 325 of the year.
This date falls on a Saturday.
In 2020, this date falls on a Saturday.
In 1981, New Year's Day falls on a Thursday.
```

__Example run__
```
Pick a date, any date (such as your birthday!)
What is the month? (1-12)? 7
What is the day? 29
What is the year? 1982
This is day number 210 of the year.
This date falls on a Thursday.
In 2020, this date falls on a Wednesday.
In 1982, New Year's Day falls on a Friday.
Would you like to pick another date? (y for yes): y

Pick a date, any date (such as your birthday!)
What is the month? (1-12)? 11
What is the day? 21
What is the year? 1981
This is day number 325 of the year.
This date falls on a Saturday.
In 2020, this date falls on a Saturday.
In 1981, New Year's Day falls on a Thursday.
Would you like to pick another date? (y for yes): y

Pick a date, any date (such as your birthday!)
What is the month? (1-12)? 2
What is the day? 14
What is the year? 2019
This is day number 45 of the year.
This date falls on a Thursday.
In 2020, this date falls on a Friday.
In 2019, New Year's Day falls on a Tuesday.
Would you like to pick another date? (y for yes): n
```

In [ ]:
%run pcalendar.py


Pick any date! (Maybe your birthday)
This is day number 325 of the year.
This day falls on a Saturday
In 2020, this date falls on a Saturday
In 1981, New Year's day falls on a Thursday
Thanksgiving falls on the 26 of that year
Thanks for using the perpetual calendar!
